# Generated by Django 4.1.7 on 2023-04-16 06:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='jsondata',
            old_name='pesstle',
            new_name='pestle',
        ),
        migrations.RemoveField(
            model_name='jsondata',
            name='added',
        ),
    ]
